### ISSUE TITLE
Test failures on Python 3.6.5

### ISSUE THREAD

**Issue by alex3kov** [jceb/dex#37]
```sh
dex --test
**********************************************************************
File "/usr/bin/dex", line 389, in __main__.Application._build_cmd
Failed example:
    Application._build_cmd('"gvim test" test2 "test \\" 3"')
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python3.6/doctest.py", line 1330, in __run
        compileflags, 1), test.globs)
      File "<doctest __main__.Application._build_cmd[4]>", line 1, in <module>
        Application._build_cmd('"gvim test" test2 "test \\" 3"')
      File "/usr/bin/dex", line 501, in _build_cmd
        raise ApplicationExecException('Exec value contains an unbalanced number of quote characters.')
    ApplicationExecException: 'Exec value contains an unbalanced number of quote characters.'
**********************************************************************
File "/usr/bin/dex", line 391, in __main__.Application._build_cmd
Failed example:
    Application._build_cmd(r'"test \\\\ \" moin" test')
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python3.6/doctest.py", line 1330, in __run
        compileflags, 1), test.globs)
      File "<doctest __main__.Application._build_cmd[5]>", line 1, in <module>
        Application._build_cmd(r'"test \\\\ \" moin" test')
      File "/usr/bin/dex", line 501, in _build_cmd
        raise ApplicationExecException('Exec value contains an unbalanced number of quote characters.')
    ApplicationExecException: 'Exec value contains an unbalanced number of quote characters.'
**********************************************************************
File "/usr/bin/dex", line 393, in __main__.Application._build_cmd
Failed example:
    Application._build_cmd(r'"gvim \\\\ \`test\$"')
Expected:
    ['gvim \\ `test$']
Got:
    ['gvim \\\\ \\`test\\$']
**********************************************************************
1 items had failures:
   3 of  25 in __main__.Application._build_cmd
***Test Failed*** 3 failures.
```

**Comment by tardypad** [comment]
Not sure if it is related to the actual same failing tests or if this another not covered case

`Exec=termite --exec "vim '\"yo\"'"`

This is valid according to desktop-file-validate utility
but also raise the following error with dex
`'Exec value contains an unbalanced number of quote characters.'`

Using Python 3.6.6

**Comment by jceb** [comment]
Thanks for reporting. I'll look into it .. there seem to be some differences with python3.

**Comment by jceb** [comment]
I disabled the failing tests for the moment. Couldn't figure out what the issue was :-/
