### ISSUE TITLE
dex traceback with service file

### ISSUE THREAD

**Issue by seblu** [jceb/dex#7]
$ dex /usr/share/kde4/services/kwalletd.desktop
Traceback (most recent call last):
  File "/usr/bin/dex", line 680, in <module>
    app = Application(f)
  File "/usr/bin/dex", line 346, in __init__
    if self.Type != 'Application':
  File "/usr/bin/dex", line 257, in Type
    return self.get_string('Type')
  File "/usr/bin/dex", line 241, in get_string
    return self._get_value(key, group=group, default=default)
  File "/usr/bin/dex", line 215, in _get_value
    self.load()
  File "/usr/bin/dex", line 186, in load
    raise DesktopEntryTypeException("'%s' is not a valid Desktop Entry because Type '%s' is unkown." % (self.filename, self.Type))
__main__.DesktopEntryTypeException: "'/usr/share/kde4/services/kwalletd.desktop' is not a valid Desktop Entry because Type 'Service' is unkown."

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/dex", line 686, in <module>
    print("Execution faild: %s%s%s" % (app.filename, os.linesep, ex), file=sys.stderr)
NameError: name 'app' is not defined

**Comment by jceb** [comment]
Support added, closing this issue.
